### ISSUE TITLE
Duplicate dictionaries with different word counts

### ISSUE THREAD

**Issue by gustavjf** [rdoeffinger/Dictionary#10]
I noticed there are a few dictionaries that are the same [language]-[language] but have different word counts. For example, there are two English-German and English-Greek. I'm not sure if this is something we have any control over but wouldn't it make sense to merge those two duplicate dictionaries into one?

Or is this just how the dictionaries are provided?

Thank you for reviving QuickDic btw, I was pretty bummed when I reinstalled it only to find out it didn't work.

![screenshot_2015-11-25-19-21-57](https://cloud.githubusercontent.com/assets/3981598/11406124/3f666faa-93ac-11e5-84e4-3cd8cd507ae8.png)

**Comment by rdoeffinger** [comment]
One is the old one from the original app, the other one that I recreated from up-to-date wiktionary.
Especially for the English-German one you can see that one has more English words and the other more German ones, so I was/am not sure if I did it correctly.
So I decided to leave both in, just in case.
It might just be a bug in how the words are counted or something though or the wiktionary data changed.
I just don't have time to come up with a way to compare what exactly the difference between these is.
Maybe it would be better to just remove the old ones, given that nobody has complained about the newly generated ones.
I might do that, but it's not a priority.

**Comment by gustavjf** [comment]
All right, that makes sense!

**Comment by rdoeffinger** [comment]
Older versions removed in c77b09285ea4b27e32e42e0ca40a280bd86bdaeb
