### ISSUE TITLE
Spanish-Spanish dic just shows plural for many words

### ISSUE THREAD

**Issue by bbo2adwuff** [rdoeffinger/Dictionary#104]
There is an issue with the Spanish-Spanish dictionary. Several words are missing that can be found on es.wiktionary.org. Surprisingly, most of the times the plural can be found.

For example, herida is missing while heridas can be found. Same with descomunal and descomunales, ahorro and ahorros, compuesto and compuestos, and so on.

However, the plural doesn’t help. heridas just tells me that it is the plural of herida.

**Comment by rdoeffinger** [comment]
I can see the issue, unfortunately that is (at least partially) an issue with the wiktionary data.
As it contains words from many languages, Spanish words need to be tagged with "== {{lengua|es}} ==".
Unfortunately the words that are missing are not tagged in such way, they only have a {{ES}} instead. I can check if there is a way to let it handle this form of tagging as well.

**Comment by rdoeffinger** [comment]
Ok, I think I fixed it. However the word "descomunal" simply does not appear in the wiktionary snapshot the dictionary is based on, and it does not seem to exist on es.wiktionary.com, so I claim innocence on that one ;-) .

**Comment by rdoeffinger** [comment]
The next app update will show the available dictionary update.
Or you can delete and re-download the dictionary to get the new one right away.

**Comment by bbo2adwuff** [comment]
Wow what a quick update! You basically fixed it quicker than I was able to respond to your comments  :rocket:
Thanks a million!

And sorry descomunal was a bad example. Didn't even realize that before :see_no_evil:
