### ISSUE TITLE
No more Czech dictionaries?

### ISSUE THREAD

**Issue by thranur** [rdoeffinger/Dictionary#108]
The app shows English-Czech in the Downloadable dictionaries, but when clicking it, nothing is downloaded. If I use the "Download in browser" feature, I'm taken to https://github.com/rdoeffinger/Dictionary/releases/v0.2-dictionaries, which has no "EN-CZ" entry.

Is the English-Czech file named differently?

**Comment by rdoeffinger** [comment]
It is "EN-CS" as far as I can tell, which is the abbreviation based on ISO 639-2.

**Comment by thranur** [comment]
Indeed, I naively assumed it would be the same as ISO-3166. I downloaded the dictionary from the Github page and it worked.
