### ISSUE TITLE
almost no space for searching by default

### ISSUE THREAD

**Issue by moshpirit** [rdoeffinger/Dictionary#11]
These buttons use a lot of space and are not practically used so this option should be disabled by default. 

Also moving the flag to the left and using the same space for the flag and the magnifying glass for changing the language.

I.e. pressing the magnifying glass or the flag change the language.

**Comment by moshpirit** [comment]
Sorry, I'm talking about the up/down buttons.

**Comment by rdoeffinger** [comment]
Latest version already removes the magnifying glass once you start typing (which was based on a suggestion by another user, so it's useful to get some idea/feedback).
Once you get used to them the up/down are actually fairly nice for looking for variants of the word especially while searching, so I am not convinced hiding them by default is a good idea.
Especially as there are quite a few phones (not to mention tablets) that have more than enough space for them.
I've thought about other options, e.g. hiding the flag if space is tight or such, but I am not really convinced they are a good idea usability-wise.

**Comment by jonathancross** [comment]
The new version already offers much more space for search box on Nexus 5. Thanks!

I agree with @rdoeffinger that combining dictionary term search and language switching into one button could be problematic for usability. It *could* be implemented as an option, but beware of feature creep. There is probably better uses if development effort.

The existing setting to "Show up/down buttons" allows for bigger search box (if disabled) and seems good enough IMHO.

**Comment by moshpirit** [comment]
Oh, OK, if the magnifying glass get hidden, then I have no problem. Thanks!
