### ISSUE TITLE
Frequency and process of dictionary update

### ISSUE THREAD

**Issue by fazlerabbi37** [rdoeffinger/Dictionary#114]
Hi, I just have a quick question about the dictionary update. How frequently does the dictionaries get updated? and I read in the README that using DictionaryPC repo we can generate dictionary but it doesn't say how to load it in the app or what to do if I want to make that generated dictionary available for others to be downloaded vai dictionary manager. Say I want to add a few words in English-Arabic dictionary and publish it for others. What would be the process? Thanks in advance.

**Comment by rdoeffinger** [comment]
You can send people the .zip file generated via DictionaryPC and install it that way.
For official updates I would need to re-generate the dictionary from Wiktionary data and then update a file in the build and create a new build.
It takes some time and I'm not sure if Wiktionary has improved enough to be worth the effort, but I probably should do it at some point.

**Comment by fazlerabbi37** [comment]
thanks for the reply @rdoeffinger :blush:. It would be great if you could take some time to document the dictionary generation process so that we the end user can do it. I think @kenden was trying to come up with a docker file to do that on issue #112. But as of now I can't verify if that work.

**Comment by rdoeffinger** [comment]
I suggest unifying this under #112 where I just posted a native Linux binary (and in theory a native Windows binary and scripts should not be impossible, but I am not sure I'll do that) and closing this one.
