### ISSUE TITLE
Feature request: Add text-to-speech option

### ISSUE THREAD

**Issue by LAfricain** [rdoeffinger/Dictionary#116]
It would be very nice to have a text-to-speech option in the App.

**Comment by rdoeffinger** [comment]
Are you aware of the "speak" option in the long-press menu? Both for words and the whole entries.

**Comment by LAfricain** [comment]
It doesn't work on my phone.

**Comment by d2weber** [comment]
> It doesn't work on my phone.

Maybe you disabled an app called "Google Text-to-Speech engine". The engine is needed for the speech synthesis to work.

**Comment by rdoeffinger** [comment]
Feature is available and working on my devices, so nothing more I can do here without further info.
