### ISSUE TITLE
entry history keeps appearing 

### ISSUE THREAD

**Issue by PthDE** [rdoeffinger/Dictionary#123]
When on search bar a drop down list of past entries appear in a plain frameleass box.
can this be disbled?
Moto G6 Android 9

**Comment by rdoeffinger** [comment]
It only (should) appear when there is nothing in the search field yet.
What is the reason you want to disable it?
From 5.5.5 there is an entry in settings where you can set the number of entries it should keep, setting it to 0 disables the search history, but I'd still appreciate to know why people want to disable it.

**Comment by PthDE** [comment]
Many thanks for the prompt reply.

Consider the use case where the dictionary (or portion thereof) is browsed that then offers/suggests a new word search. The entry is cleared, readied, but which then obstructs the required directory content being displayed. In this example the entry history is seen unnecessary.

The dictionary is very useful and easy to use. It is always in use. 

Many thanks again. 

Peter 



On 24 May 2020 19:34:38 CEST, "Reimar Döffinger" <notifications@github.com> wrote:
>It only (should) appear when there is nothing in the search field yet.
>What is the reason you want to disable it?
>From 5.5.5 there is an entry in settings where you can set the number of entries it should keep, setting it to 0 disables the search history, but I'd still appreciate to know why people want to disable it.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/rdoeffinger/Dictionary/issues/123#issuecomment-633264641
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rdoeffinger** [comment]
The thing is, when you clear the search term, the dictionary jumps to the very first entry in the dictionary (whether that's a good idea would be a different discussion :) ), which for most dictionaries is not useful.
Thus showing the list when the search entry is empty seemed like it shouldn't ever be a disadvantage?
That said I don't have a problem if you find it annoying and want it gone anyway, just checking if I miss something/if there's maybe a bug in the logic.

**Comment by anchorz** [comment]
I prefer the old Interface. My Entries in the drop down box is just a bunch of letters (1st couple of letters from words i search). I would like to have the option to clear it every now and then. Would it be possible?

**Comment by rdoeffinger** [comment]
As said in earlier comment: if you want the old behaviour, set the history entry count to 0 in settings.
This needs version 5.5.5 which is stuck in Google Play review, but F-Droid has it available and it's available here on github as well.

**Comment by rdoeffinger** [comment]
Closing on the assumption that the main issue is addressed, a way to clear the history might not be bad, but not sure it is worth the UI clutter.
