### ISSUE TITLE
Integrating with system dictionaries and long press dictionary searches

### ISSUE THREAD

**Issue by mysteryoneal** [rdoeffinger/Dictionary#127]
With android (or perhaps it is a feature of Samsung's keyboard...not sure), I can long press selected text for various shortcuts including "web search" and "dictionary search". Is it possible to get QuickDict recognized by the OS as a dictionary so this long press dictionary search feature opens QuickDict and searches for highlighted words/terms? 

Currently QuickDict is not recognized at all in the OS settings list of dictionaries.

**Comment by rdoeffinger** [comment]
That integration exists and it works at least in the emulator and on my phone (in some apps, it does not work in Firefox, but it does work in "Kolab Notes" for example).
I think that feature exists only since Android P.
I have no idea about Samsung's implementation though.

**Comment by mysteryoneal** [comment]
You are correct. I now see that there is a direct QuickDic option among the
rest of long-press popup menu options. It was hidden behind a 3-dot menu
extension button.

I froze the useless system "Dictionary" app (with Titanium Backup) and that
freed up space on the long-press menu. QuickDic is no longer hidden behind
the 3-dot button.

Works great.

**Comment by rdoeffinger** [comment]
Thanks for looking into it and confirming.
