### ISSUE TITLE
[Accessibility] Touch Target is not respected.

### ISSUE THREAD

**Issue by andreacantone** [rdoeffinger/Dictionary#135]
## Description

The size of the elements should be at least 48dp*48dp. Some elements don't respect the size of the touch target.

## How to reproduce the error

1. Activate the app [Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=it&gl=US)
2. Open the app [QuickDic](https://play.google.com/store/apps/details?id=de.reimardoeffinger.quickdic&hl=it&gl=US)
3. Activate the registration from the Accessibility Scanner and use the QuickDic app.
4. After using the app, stop the recording.

## Screenshot

The results will show the errors found in the app. For example:

![IMG_20201119_095300](https://user-images.githubusercontent.com/25429624/99646144-667ab480-2a50-11eb-991c-7b81373e66fc.png)

**Comment by rdoeffinger** [comment]
It makes no sense to run Accessibility Scanner blindly without understanding the app or its UI.
This UI element exists only for convenience, its functionality is duplicated by the floating button at the bottom.
Also note that this is a not an app-specific UI element, but one created by the Android framework, so this issue would need to be reported to Google or your phone vendor either way.
