### ISSUE TITLE
[Privacy] WebView

### ISSUE THREAD

**Issue by duggalsu** [rdoeffinger/Dictionary#138]
Opt out of sending metrics to Google when using WebView. Add the following to the manifest -
```
<meta-data android:name="android.webkit.WebView.MetricsOptOut" android:value="true" />
```
https://developer.android.com/guide/webapps/webview-privacy

**Comment by rdoeffinger** [comment]
Interesting. However:
> For users who choose to share usage statistics and diagnostics with Google
I do not think the app is sensitive enough to justify overriding a user choice, so I don't think it's a good idea to make that change.

**Comment by duggalsu** [comment]
OK, thanks
