### ISSUE TITLE
Unable to download dictionaries on Android 11

### ISSUE THREAD

**Issue by parcelcat** [rdoeffinger/Dictionary#143]
I'm not able to download any dictionaries through QuickDic on Android 11, which makes QuickDic unusable on my device. Tapping on the download button of any dictionary briefly shows a Download Manager notification that immediately disappears, and no dictionary is actually downloaded. After some time, QuickDic shows the error message "Download failed: File error."

Android 11 [enforces scoped storage by default](https://developer.android.com/about/versions/11/privacy/storage), and I have had no problems downloading dictionaries on Android 10. Could this be related to the issue?

**Comment by rdoeffinger** [comment]
The download itself is not happening in the QuickDic app but instead inside DownloadManager, so if it's aborted right away it should be something on that side.
Was the working Android 10 setup on the same device? While it should not matter as per what I said before, did you use a custom storage path in the app? If so re-installing to make it use its own app directory might be worth a try.
However it's not Android 11 in general, as it works just fine on my device for example. Issues like these also have existed for many Android generations, though never on a device I owned, nor in the Android Emulator (though I might not have tried Android 11 on that one yet).
As this issue has been recurring, the menu contains a "download in browser" option that leads you to a page where you can download the dictionaries using your browser.
After that you are supposed to be able to install the dictionary by opening the zip file with QuickDic, however that is also randomly broken on some Android devices, and then it all becomes a real pain (in essence, can extract the zip file and put the .quickdic file into the app's storage directory manually using a file manager app).

**Comment by rdoeffinger** [comment]
I just tested using the latest Android 11 image in the Android emulator and the downloads just work.
So I am afraid it must be something specific to your device or your app settings, and I am afraid I don't think I can do much about it myself at this point.

**Comment by parcelcat** [comment]
Thanks for confirming! The dictionary downloads are now working on the device, so it must have been a connection issue on my end.
