### ISSUE TITLE
Japanese kanji search reads how its read, not how its written

### ISSUE THREAD

**Issue by Nishizuki** [rdoeffinger/Dictionary#146]
Title, example would be how 君 will match all characters read as "jun", while 春 will match all characters read as "chun"

**Comment by rdoeffinger** [comment]
Thanks for pointing that out.
The basic issue here is that the dictionaries are based on a single sorted index (that's the order you see when scrolling through), and that is based on a transliteration of whatever was entered.
There is then supposed to be a second step that searches through all matches with the same transliteration to find any that are an exact match to the input, which should handle this case.
However I've only ever tested it on Spanish and it's obviously not working right for Japanese, I don't know when I will have time but I hope it is not that hard to fix and should fix the worst usability issue.
A harder to fix problem is completely relying on a transliterated index. Ideally languages like Japanese would e.g. have a secondary index that work like Japanese dictionaries do and allowed you to use it. Between lack of time and lack of Japanese knowledge on my side that probably will not happen any time soon or at all.

**Comment by rdoeffinger** [comment]
I released a fixed version so will close this one, even though it does not resolve the issue of over-reliance on transliteration.
