### ISSUE TITLE
Creating a Tolino compatible Quickdic dictionary starting with headwords, inflections and definitions

### ISSUE THREAD

**Issue by Vuizur** [rdoeffinger/Dictionary#148]
Hello,

what should I try if I had all the sufficient data (headwords, inflections and definitions) in order to create a Tolino compatible dictionary?

(I hope this question fits here)

Thank you!

**Comment by rdoeffinger** [comment]
This might be related with https://github.com/rdoeffinger/DictionaryPC/issues/8 and maybe some of the commands and examples in that issues are helpful?
