### ISSUE TITLE
Wiktionary links error

### ISSUE THREAD

**Issue by yknip0** [rdoeffinger/Dictionary#149]
Webpage not available
The webpage at http://de.wiktionary.org/wiki/anschlie%C3%9Fen could not be loaded because:

net::ERR_CLEARTEXT_NOT_PERMITTED

Perhaps this would be remedied by changing http:// to https://

**Comment by rdoeffinger** [comment]
None of my devices have such an error, and using https probably will break some older devices.
But it's probably still overall a good idea to switch https

**Comment by Efreak** [comment]
[`<application android:usesCleartextTraffic="true">
</application>`](https://stackoverflow.com/a/51902630)

**Comment by idotj** [comment]
Same problem here, running last version 5.6.2 under LineageOS 18 and 19 (both drop same error message)

**Comment by rdoeffinger** [comment]
Sorry for the delay, workaround pushed, hope to do a release soon.
