### ISSUE TITLE
Unable to download dictionaries

### ISSUE THREAD

**Issue by 9662** [rdoeffinger/Dictionary#15]
I just installed the application, then clicked on the download icon for the English dictionary. The download manager starts but does not seem to be doing anything. After a few seconds the application reports the error "Download failed: null".

**Comment by rdoeffinger** [comment]
The download manager isn't really specific to this app, so if it fails that probably means it's indeed not possible to download the file and not some app bug.
Just in case: Are you sure you installed the 5.1.x version and not the old one?
If yes, can you manually download the file at http://github.com/rdoeffinger/Dictionary/releases/tag/v0.2-dictionaries ?
If still yes, I am out of ideas, though I should probably make sure it always prints something more useful than "null".

**Comment by 9662** [comment]
Yup, version is 5.1.3 from F-Droid.
I can manually download files from that link. I have just tried with Firefox on the phone and it worked all right.
Whatever the download manager is doing, it is not downloading anything, judging by the network activity icons.

Any suggestions as to what I can do to collect some debug info? Cheers.

**Comment by 9662** [comment]
Btw, the notification from the download manager shows <Untitled> as the name of the download. Not sure if that's expected.

**Comment by 9662** [comment]
Argh! Github eats angle brackets! The previous comment should read:

Btw, the notification from the download manager shows "Untitled" as the name of the download. Not sure if that's expected.

Except that the quotes should be replaced by angle brackets instead.

**Comment by rdoeffinger** [comment]
I can tell you that it's normal for it to show Untitled as name of the download until it manages to connect with the server.
I have not yet looked at the download manager code at all so I currently have no further ideas on how to debug it.
You could add some information about your device, what kind of internet connection (via WLAN, 3G,...) and/or try on another device or on a different network.
It's not overly likely to help until I get time to review the related code, but if you don't mind it would be nice to have any such information.

**Comment by jonathancross** [comment]
I know you already said you said you checked the app version, but just thought I'd mention this: "Download failed: null" is the exact error I was getting with the old app (which prompted me to switch to this one).

**Comment by rdoeffinger** [comment]
From commit 646486e09434e65b127bf900d86b3b70fb12158b it will now print the reason why it failed, which should help with this.
Will be part of the next v5.2.0 release (with lots of other changes).

**Comment by rdoeffinger** [comment]
Version with extended download error messages is now released, tell me if you get any additional information from it.

**Comment by 9662** [comment]
@jonathancross Yes I totally checked. You can see a screenshot of the about box in [issue #13](https://github.com/rdoeffinger/Dictionary/issues/13#issuecomment-163454852).

@rdoeffinger I have tried on someone else's phone, on the same WiFi network, and the other phone did download the dictionary while mine didn't. Main difference between the two is that my phone is Google-free. I will install 5.2 when released and report back with any extra info I can gather.

**Comment by rdoeffinger** [comment]
I read up a bit and it seems many implementations of DownloadManager are buggy to a degree you wouldn't believe.
I could actually reproduce some issues on my LG G4, but there it "only" ends up sending the "download done" notification multiple times, which ends up in spurious and incorrect error messages but a still working download.
I don't think "Google-free" is a likely issue (but who knows), but more likely just a question of how broken the DownloadManager in that ROM is...
Many developers seem to implement their own download solution, but I consider that a horrible way to fix it, plus I'd have to request internet permission just for that.
Btw. 5.2.1 is out, it is available as a download here or you can wait for F-Droid which hopefully will have it soon too (I accidentally pushed the tag but not the code/commit itself, so I just hope I didn't break F-Droid).

**Comment by 9662** [comment]
F-Droid 5.2.1 reports failure with error code `1004`. I found the reason though: I have most pre-installed SSL certificates disabled, including DigiCert's, which are the CA for https://github.com/ which is where the dictionaries are hosted. Enabling DigiCert CA certificates gets the thing working.

I have no idea if the DownloadManager provides enough info that one can figure out what the error is, I have had issues with [other](https://github.com/osmandapp/Osmand/issues/1837#issuecomment-166385835) applications [also](https://github.com/theScrabi/NewPipe/issues/66#issuecomment-166386200) and they also fail to give helpful information as to what the error is, unlike say a desktop web browser which will clearly tell you, for example, that it does not trust a certificate in the chain.

Thanks a lot for looking into this. :-)

**Comment by rdoeffinger** [comment]
I'm afraid the DownloadManager is really bad/basic, it can basically report status codes and select few specific errors, but there is none for certificate errors.
I could probably suggest checking certificates for 1004 code, but not sure that's a good idea as it's a very generic error (ERROR_HTTP_DATA_ERROR). Well, actually there is no information whatsoever on what can trigger most of those error codes anyway unfortunately.
I'll keep my eyes open for good solutions, HTTPS errors might be kind of nice to handle as they will also happen when the date is set incorrectly.
(Then  again there is a question whether I should use HTTPS at all admittedly - I _think_ I have plugged the deserialization security issues in the latest version so there should be limited risk from using plain HTTP and it would also work nicer with caching/proxies)

**Comment by 9662** [comment]
It does appear to be a problem with Android not being too explicit about certificate problems, as no Android application I know of offers any sort of helpful information in this situation. Perhaps it would be helpful to open an issue upstream with the Android / Cyanogenmod guys and leave it at that.

I don't think it is an application issue as such from what I've seen, so I wouldn't worry about it. :-)

**Comment by esotericDisciple** [comment]
The app doesn't recognize browser-downloaded dictionaries that are copied directly into the data dir, either. It actually deletes the file when downloads are attempted...Both local storage and sdcard storage have the same issue
