### ISSUE TITLE
Activity memory leak caused by anonymous threads

### ISSUE THREAD

**Issue by cuixiaoyiyi** [rdoeffinger/Dictionary#154]
# Possible Memory Leak
An [anonymous inner class](https://stackoverflow.com/questions/17778077/would-anonymous-handler-or-runnable-create-a-memory-leak) will hold a reference to the this pointer of the outer class and will not be released until the thread ends.
It will hold the Activity and prevent its timely release. Please check the links below.

# Occurrences
[onCreate](https://github.com/rdoeffinger/Dictionary/blob/master/src/com/hughes/android/dictionary/DictionaryActivity.java#L542)

# Possible Solution
If it is necessary, it can be changed to [static class + weak reference](https://stackoverflow.com/questions/22162642/will-handler-inside-a-method-leak-memory/27825703#27825703) to eliminate the reference to the activity, which may cause memory leaks.
Further discussion is welcome.

**Comment by rdoeffinger** [comment]
The thread is immediately started and will terminate after a short time (usually milliseconds). None of the problematic scenarios described in the links seem possible.

**Comment by rdoeffinger** [comment]
Don't think there is anything to do here.
