### ISSUE TITLE
is this project still alive?

### ISSUE THREAD

**Issue by cmdtstof** [rdoeffinger/Dictionary#156]
dear QuickDic contributors
is this project still alive?
i am asking cause i like and use QuickDic daily
and try to find a way to add transliterations to the existing EN-TA dic (maybe via [1]).
thanks for yur work till now and thanks for an answer, which would give me the motivation for going further.
stof
[1] http://sangam.tamilnlp.com/tamil2ipa.html

**Comment by rdoeffinger** [comment]
I've not spent much time on it lately, mostly because it works very well for me and other things were more interesting
But I am still around.
It seems to me that wiktionary already contains transliterations? Would just need to parse them out and preserve them - I'd prefer to not add a new dependency for this.

**Comment by cmdtstof** [comment]
thanks for answering.
now i just need find time and the motivation to go further...
maybe someone else joins me?

**Comment by rdoeffinger** [comment]
The app is still being updated. I published one in April.
If I completely stopped, the app would be removed from the Play Store within 2 years, so the dictionary updates would be the smallest issue.
If ignoring the Play Store, F-Droid could still take patches.
But none of this has really anything to do with Dictionaries, app updates are only needed for the convenient download process via the Dictionary Manager. It's possible to download Dictionaries with a browser and install them in the app, no changes to the app required.
How to generate new Dictionaries is documented in the https://github.com/rdoeffinger/DictionaryPC project, however it is not an easy process, and I expect anyone that manages that would also manage to make new releases of the app.
But I don't have the impression that wiktionary content changes all that much, so not sure if there is really a need to update the dictionaries anyway.
