### ISSUE TITLE
Fix software keyboard popup after pressing up/down buttons

### ISSUE THREAD

**Issue by Kteby** [rdoeffinger/Dictionary#19]
Software keyboard alternately pops up and disappears while navigating through the dictionary using up/down buttons.

These buttons are useful when scrolling the list and reading words from new language to learn them, because it's much easier to press one button then to swipe the screen all the time. But popping up keyboard screws the whole learning process. It seems like pretty straightforward issue to fix, but i want to report it here before diving into project's source code.

**Comment by rdoeffinger** [comment]
I suspect it would be because it fills the search field with the new word.
Even though it doesn't have focus afterwards.
I'm fairly new to Android myself though, so I don't really know which things exactly trigger the keyboard appearing...
Worst case, forcefully hiding it after the button handling probably would work, but that seems a bit messy.

**Comment by Kteby** [comment]
Yes, 
i'm also completely new to android.

I'll try to fix this when i return back home after 8 january. I have one friend who is developing for android, so i can ask him to help.

**Comment by rdoeffinger** [comment]
Please tell me in case it becomes clear you won't be able to take care of this for whatever reason, then I'll have a look.

**Comment by Kteby** [comment]
I'll look at it, but my coworker is ill right now and i'm in a process of getting comfortable with working long hours after holidays. But i steel learning esperanto and using this app, so i'll try to fix it as soon as i can.

**Comment by rdoeffinger** [comment]
That's totally fine, just want to make sure you tell me in case you give up.
I suspect something needs to be added around the setSearchText and defocusSearchText (if a function for that exists, just hiding the keyboard in the latter might work though probably a bit ugly).

**Comment by rdoeffinger** [comment]
Fixed by merged pull request in 56c7d964a83199140532764b9ecf05594a2e8531
