### ISSUE TITLE
Go to random word

### ISSUE THREAD

**Issue by irregularisnotrandom** [rdoeffinger/Dictionary#20]
Hi

It would be very nice if there was an interface item that opens a random wprd frpm the current language.

Thanks

**Comment by rdoeffinger** [comment]
It wouldn't be too hard to do, but with the many weird words most dictionaries have I am not sure how useful it would be.
The biggest challenge would be how to add it in a way that is reasonably convenient without disturbing the majority of users not needing it.
If you think it would be good enough if it was an entry in the menu I would consider implementing that.

**Comment by irregularisnotrandom** [comment]
I am personally fine with any method, random words is helpful for language studies. However it would be nice if it is accessjble. I recommend a right to left tap gesture instead of a menu ite .

**Comment by rdoeffinger** [comment]
I'm fairly certain that any kind of tap/swipe triggering this would result in about half of the people thinking it's a bug or at least trigger it by accident.
And a lot of people who'd want this feature wouldn't find it.
cc5c3a2407180de0569c2536a2fa37ce782dd55c adds a menu item.
No promises on when the next release with it will be though.

**Comment by irregularisnotrandom** [comment]
Thanks for implementing it
