### ISSUE TITLE
Crash when trying to download dictionaries

### ISSUE THREAD

**Issue by spinclick** [rdoeffinger/Dictionary#25]
Hello. When attempting to download dictionaries, quickdic is crashing with "Unfortunately, quickdic has stopped". This occurs when pressing the download button on any of the downloadable dictionaries. I've used alogcat to retrieve some (hopefully useful) debugging output.

OS: Cyanogenmod 11 M12 (4.4.4 kitkat)

Here's the exception from the process (retrieved from alogcat):

`alogcat.2016-01-28-00-01-09-0500.txt:D/AndroidRuntime( 3083): Shutting down VM
alogcat.2016-01-28-00-01-09-0500.txt:W/dalvikvm( 3083): threadid=1: thread exiting with uncaught exception (group=0x41abbce0)
alogcat.2016-01-28-00-01-09-0500.txt:E/ActivityThread( 3083): Failed to find provider info for downloads
alogcat.2016-01-28-00-01-09-0500.txt:E/AndroidRuntime( 3083): FATAL EXCEPTION: main
alogcat.2016-01-28-00-01-09-0500.txt:E/AndroidRuntime( 3083): Process: de.reimardoeffinger.quickdic, PID: 3083
alogcat.2016-01-28-00-01-09-0500.txt:E/AndroidRuntime( 3083): java.lang.NullPointerException
alogcat.2016-01-28-00-01-09-0500.txt:E/AndroidRuntime( 3083): 	at com.hughes.android.dictionary.DictionaryManagerActivity.a(Unknown Source)
alogcat.2016-01-28-00-01-09-0500.txt:E/AndroidRuntime( 3083): 	at com.hughes.android.dictionary.DictionaryManagerActivity.a(Unknown Source)
alogcat.2016-01-28-00-01-09-0500.txt:E/AndroidRuntime( 3083): 	at com.hughes.android.dictionary.ba.onClick(Unknown Source)
alogcat.2016-01-28-00-01-09-0500.txt:E/AndroidRuntime( 3083): 	at android.view.View.performClick(View.java:4445)
alogcat.2016-01-28-00-01-09-0500.txt:E/AndroidRuntime( 3083): 	at android.view.View$PerformClick.run(View.java:18446)
alogcat.2016-01-28-00-01-09-0500.txt:E/AndroidRuntime( 3083): 	at android.os.Handler.handleCallback(Handler.java:733)
alogcat.2016-01-28-00-01-09-0500.txt:E/AndroidRuntime( 3083): 	at android.os.Handler.dispatchMessage(Handler.java:95)
alogcat.2016-01-28-00-01-09-0500.txt:E/AndroidRuntime( 3083): 	at android.os.Looper.loop(Looper.java:136)
alogcat.2016-01-28-00-01-09-0500.txt:E/AndroidRuntime( 3083): 	at android.app.ActivityThread.main(ActivityThread.java:5146)
alogcat.2016-01-28-00-01-09-0500.txt:E/AndroidRuntime( 3083): 	at java.lang.reflect.Method.invokeNative(Native Method)
alogcat.2016-01-28-00-01-09-0500.txt:E/AndroidRuntime( 3083): 	at java.lang.reflect.Method.invoke(Method.java:515)
alogcat.2016-01-28-00-01-09-0500.txt:E/AndroidRuntime( 3083): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
alogcat.2016-01-28-00-01-09-0500.txt:E/AndroidRuntime( 3083): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
alogcat.2016-01-28-00-01-09-0500.txt:E/AndroidRuntime( 3083): 	at dalvik.system.NativeStart.main(Native Method)
alogcat.2016-01-28-00-01-09-0500.txt:I/Process ( 3083): Sending signal. PID: 3083 SIG: 9
alogcat.2016-01-28-00-01-09-0500.txt:I/ActivityManager(  583): Process de.reimardoeffinger.quickdic (pid 3083) has died.`

Here is the entire alogcat session:
[alogcat.2016-01-28-00-01-09-0500.txt](https://github.com/rdoeffinger/Dictionary/files/107736/alogcat.2016-01-28-00-01-09-0500.txt)

**Comment by spinclick** [comment]
I'm not familiar with the project's code, but I think the crash is coming from somewhere in the [downloadDictionary](https://github.com/rdoeffinger/Dictionary/blob/master/src/com/hughes/android/dictionary/DictionaryManagerActivity.java#L614) method, since it's called in response to the button being clicked.

**Comment by spinclick** [comment]
Ahh, It appears this crash was caused by my own doing!

I had disabled Android's "Download Manager" app, which is required for quickdic's download functinoality to work.

Re-enabling it in the settings prevents this occuring. My apologies if I had wasted anyone's time!

**Comment by rdoeffinger** [comment]
No worries. That you somehow "broke" the download manager was my first idea, I just never got around to asking you. So no time wasted.
