### ISSUE TITLE
Bug: multiple downloads

### ISSUE THREAD

**Issue by homersimpsons** [rdoeffinger/Dictionary#28]
Why is it possible to download 7 times at once the same dictionary ??
When you press the download button of a dictionary currently downloading it add the download with 'the-name-5' for example.

**Comment by homersimpsons** [comment]
I understand, this happen because quickDic use an external downloader. Maybe it could be better to use a proper downloader...

**Comment by rdoeffinger** [comment]
When you press download, the current version will change the download button into an X that when pressed will cancel the download.
If that's not happening that most likely means the download manager app on your phone is broken.
While I considered other solutions, they are messy enough that I lean towards instead recommending to see this as a hint to in the future buy from companies that at least test their products before selling it (or if possible switch to a custom ROM).
If I had a phone affected by this I'd probably look into what can be done about it though, but so far all mine work (mostly) fine.

**Comment by homersimpsons** [comment]
I use the default download manager in v6.0.1 from Google. In fact I view the 'x' to cancel but it didn't work. So I have manually deleted the download with the download manager. By the way it's only once so no problem...
You can consider this ticket close if you want 😃

**Comment by rdoeffinger** [comment]
That's interesting! It works fine on my LG G4 with Android 6.0. Which is weird since OEMs usually add bugs, not fix them, so I would have expected a Google version to work at least as well.
Well, I might look through the code at some point, just to make sure I didn't just forget to handle something right.

**Comment by homersimpsons** [comment]
Maybe it's because I had lost the network while it was downloading ...

**Comment by rdoeffinger** [comment]
Thanks! That hint allowed me to reproduce it.
Even though I don't know why paused downloads behave differently (my code that checks the URI to find out if a download is already happening suddenly no longer finds it and thus starts a new one - and yes I do ask for a list including paused downloads).
I'll try setting a title for the download (which is a good idea anyway) and see if that at least also works for finding paused downloads.

**Comment by homersimpsons** [comment]
I wish you will find how to correct it then 😃

**Comment by rdoeffinger** [comment]
I think 6608106e36d6488340c47b69947ca467b5785ba7 and 969ea0063628e074662e7f04e50d9d509e5c1073 fixed it.
