### ISSUE TITLE
IT - RU

### ISSUE THREAD

**Issue by AlphaOmega3** [rdoeffinger/Dictionary#44]
Hi! Is possible add Italian - Russian dictionary??

**Comment by rdoeffinger** [comment]
I generated it and you can manually download it from here and install it into the dictionary data directory:
https://github.com/rdoeffinger/Dictionary/releases/download/v0.2-dictionaries/IT-RU.quickdic.v007.zip
It will also be downloadable from the app with the next release, but it might be a while before I publish the next release.

**Comment by rdoeffinger** [comment]
Forgot to say: untested. Reopen if there are issues with it.
