### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by AlfaOmega33** [rdoeffinger/Dictionary#47]
Add an ability to work with Orbot/I2P services

**Comment by rdoeffinger** [comment]
Downloads are not something that the app handled, but Android's system download manager, thus such proxy support needs to be added there.
If there is a third-party app that provides an API to use it as a replacement for the system download manager supporting that is an option as well, but I would need to know the name of that app and its documentation.
Of course, manually downloading and extracting the dictionaries is always an option (they can be found on the releases page).
Custom download code however has no place in a dictionary app and I won't add any such code.

**Comment by AlphaOmega3** [comment]
Okay, thank you for the same response. however, the only alternative download manager to the "standard" is GigaGet (https://github.com/PaperAirplane-Dev-Team/GigaGet), but at the moment the development is stopped.

**Comment by rdoeffinger** [comment]
I understand this might be nice, but I am afraid this is out of scope unless this project somehow gains a lot more people working on it.
