### ISSUE TITLE
Feature Request: Option to put the bar at the bottom

### ISSUE THREAD

**Issue by moshpirit** [rdoeffinger/Dictionary#48]
I use a lot this app (thanks so much) and I use it with 3 languages: Spanish, English and Portuguese so I'm constantly changing the language. I think it would be very much comfortable if we had the flag icon nearer to the finger. A solution for this could be having the bar at the bottom of the screen or between the search bar and the menu  button (or both).

**Comment by rdoeffinger** [comment]
Bar at the bottom would be quite non-standard UI, so I don't think that is a good idea.
I would propose a floating button
![screenshot_20161027_024944](https://cloud.githubusercontent.com/assets/5464937/19748003/76e64a68-9bdf-11e6-9e00-898edb7a0403.png)
, even though it does take up a good bit of space.

**Comment by moshpirit** [comment]
Oh, nice idea! But I think we should be able to hold it too just like the flag button.

**Comment by rdoeffinger** [comment]
Yes, long press is working the same.

**Comment by moshpirit** [comment]
Cool!! Then it's a very good solution!! Thank you! :-)

**Comment by rdoeffinger** [comment]
Implemented, on beta channel in play store.
Full release (which will then also appear on github and fdroid) will happen later after finishing and testing some other features.

**Comment by moshpirit** [comment]
Cool! Thank you!! So when may I expect approximately to see the new version on F-droid? :-)

**Comment by rdoeffinger** [comment]
I'll probably take a few days to test on my side.
Then it seems F-droid had some issue with their automation not handling the app being split over two repositories well so they have to manually trigger the release on their side.
Who knows how long that may take, as I think they don't really have the manpower for that kind of manual steps (nor do they have any system that would allow me to conveniently do it myself - also the reason I don't support beta releases on it).
So the real answer on that is: As much as I'd like to officially support it, I consider what happens concerning F-droid releases out of my control.

**Comment by moshpirit** [comment]
I knew about F-droid, it usually takes less than a week so I think I'll have the new version in more or less a week, which is less than what I expected :-) thanks a lot for your work and this complete answer!

**Comment by rdoeffinger** [comment]
Finished the tests I could think of, so the release is now out.
