### ISSUE TITLE
Fileformat

### ISSUE THREAD

**Issue by gobezu** [rdoeffinger/Dictionary#51]
Is there a file format definition I can use to create a dictionary file for additional languages I am considering.
Thank you for your work.

**Comment by rdoeffinger** [comment]
There is the code and scripts in the DictionaryPC directory to create dictionaries.
The v6 format relies on Java serialization/deserialization, so specifying it is not remotely a realistic task.
v7 should be more reasonable to specify but it relies on chunked compression, Java's "modified UTF-8" and features like that which make it a bit of a pain.

**Comment by rdoeffinger** [comment]
See:
https://github.com/rdoeffinger/Dictionary/blob/master/dictionary-format.txt
But I am not so sure you will still want to implement it after reading that...

**Comment by rdoeffinger** [comment]
Was this of any use? I am happy to add clarifications/improvements, but I don't really want to spend time on that unless it will actually be used.
