### ISSUE TITLE
Font size pref doesn't change the font inside definitions

### ISSUE THREAD

**Issue by akkana** [rdoeffinger/Dictionary#52]
The font size pref is great for the word list, but the font inside definitions is still tiny. It would be great to have a way to increase that size.
(BTW, thanks for QuickDic, great app!)

**Comment by rdoeffinger** [comment]
What do you mean by "inside definitions"?
Do you mean the web page view when following links?
There is no really nice way to adjust that one, as it's basically the system settings that determine the default size etc (but I am not sure these systems settings can be changed).
You can of course use zoom gestures to scale that, but it doesn't re-wrap the content in that case, so it's not very nice. Not sure if that can be changed.

**Comment by akkana** [comment]
Not the web page view, but the definition page inside QuickDic after you tap on a word. The font size setting seems to have no effect on the font size there. So, in these screenshots, the font size in the wordlist (cañada, cañadas, caña de azúcar, etc.) gets bigger if I change the font preference, but the font size in the definitions of the word (From the Latin canna, es-noun|f etc.) never changes.
![screenshot-wordlist](https://cloud.githubusercontent.com/assets/1451863/22176864/4c884af2-dfd0-11e6-9b82-88c8e07dfb14.png)
![screenshot-definition](https://cloud.githubusercontent.com/assets/1451863/22176870/5749eaae-dfd0-11e6-9895-3833a9434108.png)

**Comment by akkana** [comment]
Just occurred to me -- did you mean that second (definition) view is implemented as a webview? Is that html_display_activity? If so, one way to change the font size is to use a local stylesheet where the preferred font size is stored, and modify the CSS when font size changes. Another possible way (I can't verify it works, but some people seem to use it) is:
WebSettings webSettings = webView.getSettings();
webSettings.setDefaultFontSize(fontsize);

**Comment by rdoeffinger** [comment]
Ah, I had only seen setTextSize which was deprecated. setDefaultFontSize sounds like it might indeed be the right thing to do. The CSS approach sounded to me like it would possibly result in inconsistent sizes since it doesn't quite use the same units (but I might have misunderstood - and if I didn't it might be that setDefaultFontSize has the same issue).
Anyway, I'll put that on my TODO list.

**Comment by rdoeffinger** [comment]
Should be fixed by 9ab8426aee0ae142d0343d172917c6def470cb51
