### ISSUE TITLE
searchin/sorting in English-Norwegian not correct

### ISSUE THREAD

**Issue by m-derrer** [rdoeffinger/Dictionary#53]
Hi!

Typing "thank" in English to Norwegian searching/sorting always stops at the thorn letter, while below I can find than, thank, that, the, ...

Thanks for your work!

Yours
Matthias

**Comment by rdoeffinger** [comment]
Thanks for the report.
That kind of thing happens when Desktop Java and Android disagree on in which way words should be sorted.
I'll have to add a special case for it (as I already did for words containing a dash), might take a bit before I have time for it though.

**Comment by m-derrer** [comment]
Hi Raimar,

no problem - take your time! I didn't want to complain anything, but only wanted to give a hint for future improvement, as a small part of participation. So because of a free app, it's up to me to say thankyou for finding any word :-) Great App!

And ... because it might be possible, that you're German, here in your (and my language):

Hallo Raimar,

kein Problem - nimm dir die Zeit, die du brauchst! Ich wollte mich ja nicht über irgendetwas beklagen, sondern nur einen Hinweis geben für zukünftige Verbesserungen, als kleinen Teil einer Mitarbeit. Deshalb: Weil es ja eine kostenlose App ist, ist es an mir hier Danke zu sagen, dass ich überhaupt irgendein Wort finde : -) Großartige App!

DANKE und herzliche Grüße
Matthias

**Comment by rdoeffinger** [comment]
Fixed in fb347ae25036b89de22f48c7b710ed36b7be4440

Danke, keine Sorge ich sehe Fehlerberichte auch ohne besondere Erklärung als Mithilfe und nicht Beschwerden :)
