### ISSUE TITLE
RO is not Romanche in french but Romanian, but why do we translate this?

### ISSUE THREAD

**Issue by Jibec** [rdoeffinger/Dictionary#55]
Hi,

this looks wrong: https://github.com/rdoeffinger/Dictionary/blob/master/res/values-fr/languages.xml#L66
RO is Romanian in english, Roumain in french.

But I do not really understand why we have to translate such lists, as the content is already included in standards.

From this link: http://stackoverflow.com/questions/7973023/what-is-the-list-of-supported-languages-locales-on-android
I went to this page: https://developer.android.com/reference/java/util/Locale.html
I understand "getDisplayName" will give you the correct translated version of the language:
`new Locale("en").getDisplayName(Locale.FRANCE) -> anglais `

Thanks a lot for your help and this software, I like it very much!

**Comment by rdoeffinger** [comment]
That code is fairly old and I don't know if there is any good reason. It might be that feature didn't work well in old versions of Android for example, or it might cause issues with special cases like ancient greek or Mandarin.
But otherwise your suggestion seems like a very good idea.

**Comment by rdoeffinger** [comment]
Fixed in 3389791a1013da2765849c6da30aad3f11264387.
But your suggestion at least in Android 2.3 doesn't work for "cmn" (Mandarin), so Ieft the manual translations in as fallback.
