### ISSUE TITLE
Do not use flag for language

### ISSUE THREAD

**Issue by Jibec** [rdoeffinger/Dictionary#56]
it would be great to only use names and not flags to identify languages.
If any interest, here is a full article about this subject: https://www.cs.tut.fi/~jkorpela/flags.html

But we may only keep this short quotation:
> The CEN Workshop Agreement European Culturally Specific ICT Requirements says:
> > The use of national flags to denote language, although convenient to implement, is another potential source of major irritation to the users, particularly for native speakers of the language outside the thus indicated country.
> > Source (in PDF format): CWA 14094, clause 5.9

thanks for your help and this great software!

**Comment by rdoeffinger** [comment]
Especially in this context I find the arguments of that article fairly weak.
First, it doesn't matter if people recognize the flag (plus, who says people would recognize the ISO abbreviation of the language, not to mention that this right out assumes familiarity with the latin alphabet, so the article is quite showing some biases of its own right there), the names are also there right next to it.
The flags are very recognizable and make it much faster to find the right language in a long list, and if you don't know the flag originally you will end up learning it quite quickly.
Maybe more importantly though, e.g. for French the dictionary is in indeed primarily for French as spoken in France, so there is a distinct connection to the country.
Which kind of leaves the "could be taken as an insult" argument. There might be causes where it's more questionable and I could imagine cases where extra sensibility might be warranted, but I do not feel it is a good trade-off to reduce usability for the majority to avoid a minority feeling bad about being reminded that their native language is generally closely associated with a different country.
If there was a equivalent-or-better way of doing it, that would of course change things, but I don't see one.

**Comment by dllud** [comment]
I've heard this argument a few times now.
Using flags would be wrong if QuickDic was exclusively using flags (as many websites still do nowadays). Instead it is using them as a visual aid alongside the language's full name.

As @rdoeffinger points out, the only argument that stands is the insult one. I do agree with him that it is worth to annoy the few that have strong political views on this matter in exchange for the ease of navigation that flags provide.

**Comment by Jibec** [comment]
I'm glad to see you gave a clear answer after reading it and assuming the decision.
I'm not harmed by this decision (I'm from France) and I close the ticket.

Though, on a philosophical point of view, free software also means values and an ideal. I do not feel confident about rejecting people because of "strong political views", if harmed, it matters. Debian for example wrote it explicitly in his rules "No discrimination against persons or groups.".
French translators for the example, try not to assume the user is a male. Same thing.
I stop trolling, I love your app :)
