### ISSUE TITLE
Remove dots from strings in Menu

### ISSUE THREAD

**Issue by mueller-ma** [rdoeffinger/Dictionary#59]
I would like to change "Settings..." to "Settings". I haven't seen these dots in any other app at this point

**Comment by rdoeffinger** [comment]
I guess the idea was like for Desktop apps that dots would indicate entries that do not cause any immediate actions but instead just lead you to another screen.
It might be useful to make more obvious which items are "safe" to click just to explore the app and which ones might cause things to happen.
I haven't checked if there actually is any real value to that though, and I don't feel strongly about it wither way.
If you think changing it is better I expect I'm fine with merging a pull request.

**Comment by rdoeffinger** [comment]
Merged

**Comment by rdoeffinger** [comment]
Oh, missed your other point about the order. Yes, I always thought the order was rather bad, I just couldn't decide on a better one :)
I don't have an Android IDE around over the holidays so I don't think I'll change it over the next weeks (unless you send a pull request for that, too), but I'm happy to go with your suggestion.

**Comment by rdoeffinger** [comment]
The order hopefully is a good bit better with 1c929d8
