### ISSUE TITLE
Round buttons disappear when search returns no results

### ISSUE THREAD

**Issue by dllud** [rdoeffinger/Dictionary#63]
![no-results-no-buttons](https://cloud.githubusercontent.com/assets/1716156/21861640/9687d820-d82d-11e6-8d1c-9a843515cef6.png)

The materialish round buttons disappear when a search returns no results. They would be as useful here as in any other context, specially the `X` button to clear your search.

**Comment by rdoeffinger** [comment]
Ah, that's simply a bug, not intentionally so. I never noticed because this page only appears when you enter multiple words, a feature I almost never use myself.

**Comment by rdoeffinger** [comment]
Feels like an Android bug.
Fixed/worked around in a58cddc5e89581a2e508298cd3fc013fb2d55b37.
