### ISSUE TITLE
Various German Localisation Typos

### ISSUE THREAD

**Issue by ksaerdna** [rdoeffinger/Dictionary#67]
This text in the GUI:
`"Dieses Wörterbuch wird benutzt, wenn kein Anderes explizit abgegeben ist".`
should be:
`"Dieses Wörterbuch wird benutzt, wenn kein anderes explizit angegeben ist".`
Note the wrong capital "A" (a common typo since German othography was deliberately destroyed in 1996). Also I think it should be "angegeben" (== specified), not "abgegeben" (== delivered).

Similar:
`"... das Vorherige und Nächste Wort ..."`
Note the wrong capitals "V" and "N, also a typical post-1996-typo.

Further:
`"Definition der Wörterbuchschrift"`
is a non optimal wording and might be better something like this:
`"Festlegung der Wörterbuchschriftart"`
or shorter and easier:
`"Wörterbuchschriftart festlegen"`
as I suppose it means "character font".

Another one:
Open "Über QuickDic" and see the following text:
`"... enthält Programmcode, der unter der Apache 2.0 Lizenz steht..."`
which must be
`"... enthält Programmcode, der unter der Apache-2.0-Lizenz steht..."`
. Note the two missing hyphens ("-").

**Comment by rdoeffinger** [comment]
Soweit ich das Nachschlagen konnte ist "Anderes" eher nur etwas komisch als falsch.
Und mit genug Eile braucht man auch gar keine Rechtschreibreform um solche Fehler hinzubekommen - oder zumindest zu übersehen :)
Sollte geändert sein, es gibt aber sicher noch weitere Formulierungen die nicht gerade optimal sind...
