### ISSUE TITLE
Bug: QuickDic crashes when I alternate the translation

### ISSUE THREAD

**Issue by moshpirit** [rdoeffinger/Dictionary#73]
Steps:

1. Open QuickDic (English - Spanish in my case)
2. Press the X button

I also noticed that when I press the flag button, I only see the "dictionary manger button" and not the 3 differ dictionaries I have. Maybe the bug is that QD doesn't manage them correctly. 

It didn't happen before, I'm using v. 5.3.9 on Android 6.0.1

**Comment by rdoeffinger** [comment]
5.3.9 is/was not a fully stable version, but can't really mark it as such in F-droid.
5.4.0 has been released since a while and F-Droid shows it as successfully built, I don't know why it hasn't appeared yet, but either way I expect this is already fixed, just need to wait for the new version.
