### ISSUE TITLE
Translate intent

### ISSUE THREAD

**Issue by gsantner** [rdoeffinger/Dictionary#74]
Hi there,
is there any Intent I can send to translate something with QuickDic? So if I have another application and click on "look for translations" it may open QuickDic in specified from-to language and search for the word.

**Comment by rdoeffinger** [comment]
There are several, the full list is in AndroidManifest.xml:
android.intent.action.PROCESS_TEXT
android.intent.action.SEND
android.intent.action.SEARCH

These just go through the installed dictionaries in order and pick the first containing the word.

com.hughes.action.ACTION_SEARCH_DICT
allows specifying a QUERY and in addition "from" and "to" string extra to select a dictionary.
Even specifying "dictFile" is supported, but I wouldn't recommend that one (not even sure it really works).

**Comment by gsantner** [comment]
Thanks for response! Is there any documentation on these available, that is special for QuickDic, or is everything working like document in android's dev documentation?

**Comment by rdoeffinger** [comment]
The first 3 only exist for interaction with Android and seem to work fine for that, so yes they should exactly follow the documentation.
The last one is specific to QuickDic, I don't think there's any documentation, I have never used or tested it (so I can only hope it actually works). Though what I described is hopefully enough to figure it out, it's not really complicated.
