### ISSUE TITLE
/mksmallicu.sh

### ISSUE THREAD

**Issue by den4ikrude** [rdoeffinger/Dictionary#76]
getting this error when building with android studio
and gradle wrapper and gradle build tools latest version
`Error:Execution failed for task ':makesmallicu'.

A problem occurred starting process 'command './mksmallicu.sh''`

I need your help!!

**Comment by rdoeffinger** [comment]
Please see the already open issue #68 and answer the question there.
Without even knowing which OS or exact versions of anything all I can tell is "works for me and others, e.g. F-Droid" (and, as also mentioned in the other ticket, that you can disable this completely optional step).
