### ISSUE TITLE
Cannot extract downloaded dictionaries

### ISSUE THREAD

**Issue by madmage** [rdoeffinger/Dictionary#8]
Hi, I am not able to download and install any new dictionary, it always downloads it but fails the extraction.

**Comment by rdoeffinger** [comment]
Can you quote the exact error message, just to be sure?
Also, did you happen to change the storage location to an external SD card?
I recently got a report where that seemed to be the cause (though I do not yet understand why/how).

**Comment by madmage** [comment]
It says (the message is in Italian, so I am translating): "Dictionary
decompression failed: file:///storage/emulated/0/EN-EO.quickdic.v006.zip

There are 3 GB free on /storage/emulated/0

I see this only in this moment: why it is trying to decompress to the root
of the /storage/emulated/0 ?? Could it be that it has permission problems
with that directory?
The QuickDic Directory is set to /storage/MicroSD/AppData/QuickDic

On Tue, Nov 17, 2015 at 1:37 PM, Reimar Döffinger <notifications@github.com>
wrote:

> Can you quote the exact error message, just to be sure?
> Also, did you happen to change the storage location to an external SD card?
> I recently got a report where that seemed to be the cause (though I do not
> yet understand why/how).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rdoeffinger/Dictionary/issues/8#issuecomment-157360853>
> .
>



-- 
Daniele "MadMage" Calisi
*"Your limit is always a bit beyond"*

**Comment by rdoeffinger** [comment]
No need to translate, those are translated strings I can look up (plus I can understand basic Italian)
The message is bad/confusing. It is downloading to /storage/emulated/0, and the file it decompresses is there. I don't think it's a permission issue.
But the QuickDic dictionary seems to be on an external SD, so that seems consistent with the other report.
After a bit of searching, it seems using external SD cards simply isn't possible without a major hassle: https://metactrl.com/docs/sdcard-on-lollipop/
In theory if you specifically specify Android/data/de.reimardoeffinger.quickdic it is supposed to work, but it seems like there are more bugs in Android and that only works if you got that path through the APIs, not of a user entered it manually.
Best chance of fixing this is probably to implement issue #4 which can then do all the necessary magic.

**Comment by rdoeffinger** [comment]
I added a new release (here and in Google Play beta channel) that should print an error and suggest alternatives if the selected directory is not writeable.
It's a bit messy and I haven't tested it yet (I made it mostly for trying some things out myself later), but if you have time over feel free to check if it helps.

**Comment by rdoeffinger** [comment]
I think 5.1.2 release will make this work, it will warn when a directory that cannot be written is chosen an it will suggest alternatives.
This is still not as user-friendly as I'd like, but it should work for the moment I hope.
Still need to test it a bit more before releasing as stable.

**Comment by rdoeffinger** [comment]
Newest release works for me and pinpoints the issue and gives hints about possible ways to resolve.
I was able to use an external SD card that way.

**Comment by rdoeffinger** [comment]
Reopen if you still have issues (besides bad usability which I track in that other ticket).

**Comment by madmage** [comment]
Hi Reimar,
sorry for not replying so far: I am not sure how can I install the new
version, since there is no new release on Google Play and when I install
the APK by hand, it says it has installed it, if I try to reinstall, it
says that I have version 5.1.2 and I want to install 5.1.2 (so I assume it
has been installed correctly), but the app itself, in the about screen,
says I have 5.1.0 and, above all, the behavior is the same with that bug

On Thu, Nov 19, 2015 at 9:23 AM, Reimar Döffinger <notifications@github.com>
wrote:

> Reopen if you still have issues (besides bad usability which I track in
> that other ticket).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rdoeffinger/Dictionary/issues/8#issuecomment-157987144>
> .
>



-- 
Daniele "MadMage" Calisi
*"Your limit is always a bit beyond"*

**Comment by rdoeffinger** [comment]
I seem to have forgotten updating the version string, so the version in "about" doesn't mean anything.
If it says it's up-to-date I expect that's correct. The new version is also on the Play Store now, if in the changes list the latest entry is "Error messages when choosing an invalid storage directory" you have it.
No change means you still get the "decompression failed" and not a "Dictionary location not writable" one?
Then the issue you have isn't the one I fixed I'm afraid...
I had to use /storage/MicroSD/Android/data/de.reimardoeffinger.quickdic/files for it to work.
Now that I test some more I see that my checks don't work if the directory you specified already exists, it seems the "canWrite" function does not actually work...
I'll have to look at it again, but try the path I gave above or try entering some complete nonsense to make it print suggestions, that at least should work.

**Comment by rdoeffinger** [comment]
I _think_ now the code actually works, with 5.1.3.
I also changed it so that the about page will always display the correct version, without me having to remember to change it.

**Comment by madmage** [comment]
Ok, somehow the last version arrived via Google Play updates on my
smartphone. Now it works (i.e., there is a popup message that says I am
using a non-writable directory and it offer some writable alternatives).

On Thu, Nov 19, 2015 at 10:03 PM, Reimar Döffinger <notifications@github.com
> wrote:

> I *think* now the code actually works, with 5.1.3.
> I also changed it so that the about page will always display the correct
> version, without me having to remember to change it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rdoeffinger/Dictionary/issues/8#issuecomment-158197005>
> .
>



-- 
Daniele "MadMage" Calisi
*"Your limit is always a bit beyond"*

**Comment by rdoeffinger** [comment]
Thanks for reporting back!
Now I just have to at some point make it actually user friendly :-)
Some day...
