### ISSUE TITLE
Add a QuickDic icon and screenshot to F-Droid

### ISSUE THREAD

**Issue by WPFilmmaker** [rdoeffinger/Dictionary#84]
I don't know if you directlyupload new version on F-Droid or someone there packages it, but I would like to point out that while the other version (dead and 4yo old!) has a nice icon in F-Droid store, this version does not. Furthermore the new versions of F-Droid support screenshots, therefore it would be nice having a few to show how QuickDic looks like.

**Comment by rdoeffinger** [comment]
Sorry, I do not and do not intend to maintain the F-Droid repository entry, there's only so much time in a day.
F-Droid has its own issue tracker: https://f-droid.org/en/issues/ (the second one I'd think should be appropriate for this).
Icons and screenshots are available in the repository and/or on the Play Store. For anything that is available just on the play store you may assume the same license as for the project itself (though to be honest it should be possible to create better screenshots than those).
