### ISSUE TITLE
Annoying glitch with English-Russian dictionary (QuickDic v 5.4.3 Android 7.0)

### ISSUE THREAD

**Issue by WPFilmmaker** [rdoeffinger/Dictionary#85]
I noticed that when I use the English-Russian dictionary I get an annoying glitch.
I open QuickDic (installed through F-Droid), open the English-Russian dictionary, search for a word and go back to my phone homepage. There I have F-Droid icon and an opaque square appears around it. 

I tried with another dictionary and everything was fine, so I think the glitch is cause by the English-Russian dictionary.
I don't know if this is a specific issue of the F-Droid version or not, but it would be nice to have it fixed.
Anyone?
update: Forgot to mention that this glitch was present in various version of QuickDic, it is not a recent thing.

**Comment by rdoeffinger** [comment]
I don't think this has anything to do with QuickDic.
The opaque square should be the focus marker. It's supposed to only be there when a physical keyboard, TV remote or similar is connected, but sometimes it just decides to appear "randomly".
It can happen no matter which dictionary, it can happen at least also with Android 6.0, and I'm pretty sure I've seen it happen with other apps as well (though not as frequently).
I didn't investigate what causes it, but it could be something like the code that automatically shows the on-screen keyboard.

**Comment by rdoeffinger** [comment]
I don't think it's something fixable in the app, and I have not seen this issue myself in a long time (one of my devices used to have it randomly, with different apps some time ago).
So I am closing, but of course re-open if there's any new information or otherwise a chance to do something about it.
