### ISSUE TITLE
Tag 5.4.6 version for F-Droid

### ISSUE THREAD

**Issue by Poussinou** [rdoeffinger/Dictionary#93]
Could you please tag the 5.4.6 version, so that F-Droid can build it? (see [here](https://gitlab.com/fdroid/fdroiddata/issues/1231))

**Comment by rdoeffinger** [comment]
Been on holiday, and it wasn't a release with significant changes. Done now though.

**Comment by Poussinou** [comment]
No problem thanks 👍
