### ISSUE TITLE
Any plans to build a Romani dictionary?

### ISSUE THREAD

**Issue by dphender** [rdoeffinger/Dictionary#96]
I know the answer is probably no, since I don't think there's a Wiktionary file for the Romani language, but I thought I'd put the idea out there in case anybody feels qualified to start one...

**Comment by rdoeffinger** [comment]
I have no idea about the quality, but there seems to be a reasonably significant amount of data about Romani translations in Wiktionary: https://github.com/rdoeffinger/Dictionary/releases/download/v0.2-dictionaries/EN-rom.quickdic.v007.zip
