### ISSUE TITLE
Search history

### ISSUE THREAD

**Issue by dtattam** [rdoeffinger/Dictionary#97]
I looked up a word yesterday and now I can't remember what I looked up, and it's bugging me! A little Search History feature would be great.
Thanks

**Comment by bege10** [comment]
Please, combine with https://github.com/rdoeffinger/Dictionary/issues/86

**Comment by rdoeffinger** [comment]
Aside from finding the time, I am not really sure how to best implement a search history.
Normally history is displayed above/below the search bar, but in this case that would waste valuable screen space.
So where to put it?
I guess somewhere in the menu would be possible, but it feels like that will get very awkward to use...

**Comment by bege10** [comment]
Below the search bar is not waste of space. When I tap in the search bar in other apps the history appears if there is one. As soon as I don't chose an entry in the history but start typing the history disappears. That would be fine in QickDic also.
Thanks for your work.

**Comment by rdoeffinger** [comment]
Ah, I always had a searchable history in my mind, that would stay and display matching results even when you type.
But you're right, what you say makes much more sense. I somehow never thought of it.
No promises on when I will have time (and as always I appreciate if someone else wants to implement it), but that sounds like something doable!

**Comment by rdoeffinger** [comment]
There is a small challenge in that the app does not use an explicit search button, so there is a bit of a challenge on how to decide what should be added, not every typo that you correct should get its history entry for example.
Maybe just a dumb "you have not typed anything for 2 seconds or you switched away from the app" could work. 2 seconds is pretty arbitrary though.

**Comment by bege10** [comment]
Thank you very much for considering this.
You are right, it is a bit tricky because QuickDic shows the results with every typed letter. For the moment I don't have a better idea than your 2 seconds solution.
The menu or settings should have an option to clear the history and maybe a max. number of entries.

**Comment by rdoeffinger** [comment]
Ok, here's a first version with a quick search history implementation.
It's not clever, no timeout there, just when you press the search button on the keyboard, press the clear search floating button or switch out of the app will it save the word.
Also some issues like when you dismiss the keyboard with no search text and go back to the search field by tapping it the history is not shown.
I'm sure there's more issues, and I doubt I'll get around to fix them all before whenever I will do the next release. So some testing and a kind of priority list of things to fix would help a lot.
[Dictionary-issue97.zip](https://github.com/rdoeffinger/Dictionary/files/4531622/Dictionary-issue97.zip)

**Comment by bege10** [comment]
Thank you very much. At a first glance it looks quite good. After some testing I will come back.

**Comment by rdoeffinger** [comment]
Version is now in Google Play beta, F-Droid should follow after it got some testing there.
Thus closing.
There's likely many ways that could be improved, feel free to open a new issue for that.

**Comment by bege10** [comment]
:smile:
