### ISSUE TITLE
Searching for Russian words containing the 'ь' character will often fail

### ISSUE THREAD

**Issue by engblom** [rdoeffinger/Dictionary#99]
Searching for a Russian word containing the 'ь' character will often fail. Most of the times you end up scrolling down a lot until you find it. For testing, one can search for 'весь', which is in the Russian - English dictionary but not found by searching.

**Comment by Heineken** [comment]
I confirm this issue for the RU-EN dictionary.
Seems to be an issue with this dictionary, as loooking up 'весь' in the RU-DE works fine.

**Comment by rdoeffinger** [comment]
This seems to be the usual mis-generated dictionary issue.
I'll look into re-generating all of them from scratch.
The attached one seems to be fine I think, so I think I've solved the issue, just need to publish all the new dictionaries.
[EN-RU.quickdic.v007.zip](https://github.com/rdoeffinger/Dictionary/files/4464710/EN-RU.quickdic.v007.zip)

**Comment by rdoeffinger** [comment]
Released 5.5.1 with new dictionaries which seems to fix this.
